sam3:
  ckpt_path: "path to sam3.pt"

sam_3d_body:
  ckpt_path: "path to sam-3d-body-dinov3/model.ckpt"
  mhr_path: "path to sam-3d-body-dinov3/assets/mhr_model.pt"
  # num of frames processed in parallel
  batch_size: 64
  detector_path: ""
  segmentor_path: ""
  fov_path: ""

runtime:
  output_dir: "./outputs"
